version: '3.7'

services:

  sample4:
    container_name: sample4
    build:
      context: services/app/
      dockerfile: Dockerfile
    volumes:
      - './services/app:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development