version: '3.7'

services:

  sample4:
    env_file: ".env"
    container_name: sample4
    build:
      context: services/app/
      dockerfile: Dockerfile
    volumes:
      - './services/app:/app'
      - '/app/node_modules'
    expose:
      - '3000'
    environment:
      - NODE_ENV=development
  
  sample4_nginx:
    container_name: sample4_nginx
    build:
      context: services/nginx
    ports:
      - '80:80'
    depends_on:
      - sample4